package com.example.dao;

import com.example.entity.Adjustsalary;
import java.util.List;

public interface AdjustsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated
     */
    int insert(Adjustsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated
     */
    Adjustsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated
     */
    List<Adjustsalary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Adjustsalary record);
}