package com.example.dao;

import com.example.entity.Employeetrain;
import java.util.List;

public interface EmployeetrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated
     */
    int insert(Employeetrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated
     */
    Employeetrain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated
     */
    List<Employeetrain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeetrain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Employeetrain record);
}