package com.example.dao;

import com.example.entity.Employeeec;
import java.util.List;

public interface EmployeeecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated
     */
    int insert(Employeeec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated
     */
    Employeeec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated
     */
    List<Employeeec> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeeec
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Employeeec record);
}