package com.example.dao;

import com.example.entity.Hr;
import java.util.List;

public interface HrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated
     */
    int insert(Hr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated
     */
    Hr selectByPrimaryKey(Integer id);

    Hr selectByName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated
     */
    List<Hr> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hr record);
}