package com.example.dao;

import com.example.entity.Joblevel;
import java.util.List;

public interface JoblevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated
     */
    int insert(Joblevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated
     */
    Joblevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated
     */
    List<Joblevel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joblevel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Joblevel record);
}