package com.example.dao;

import com.example.entity.MenuRole;
import java.util.List;

public interface MenuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated
     */
    int insert(MenuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated
     */
    MenuRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated
     */
    List<MenuRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuRole record);
}