package com.example.dao;

import com.example.entity.Msgcontent;
import java.util.List;

public interface MsgcontentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated
     */
    int insert(Msgcontent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated
     */
    Msgcontent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated
     */
    List<Msgcontent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msgcontent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Msgcontent record);
}