package com.example.dao;

import com.example.entity.Oplog;
import java.util.List;

public interface OplogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int insert(Oplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    Oplog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    List<Oplog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Oplog record);
}