package com.example.dao;

import com.example.entity.Politicsstatus;
import java.util.List;

public interface PoliticsstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated
     */
    int insert(Politicsstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated
     */
    Politicsstatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated
     */
    List<Politicsstatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Politicsstatus record);
}