package com.example.dao;

import com.example.entity.Sysmsg;
import java.util.List;

public interface SysmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated
     */
    int insert(Sysmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated
     */
    Sysmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated
     */
    List<Sysmsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysmsg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sysmsg record);
}