package com.example.entity;

import java.io.Serializable;
import java.util.Date;

public class Adjustsalary implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.eid
     *
     * @mbg.generated
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.asDate
     *
     * @mbg.generated
     */
    private Date asdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.beforeSalary
     *
     * @mbg.generated
     */
    private Integer beforesalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.afterSalary
     *
     * @mbg.generated
     */
    private Integer aftersalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adjustsalary.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adjustsalary
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.id
     *
     * @return the value of adjustsalary.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.id
     *
     * @param id the value for adjustsalary.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.eid
     *
     * @return the value of adjustsalary.eid
     *
     * @mbg.generated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.eid
     *
     * @param eid the value for adjustsalary.eid
     *
     * @mbg.generated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.asDate
     *
     * @return the value of adjustsalary.asDate
     *
     * @mbg.generated
     */
    public Date getAsdate() {
        return asdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.asDate
     *
     * @param asdate the value for adjustsalary.asDate
     *
     * @mbg.generated
     */
    public void setAsdate(Date asdate) {
        this.asdate = asdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.beforeSalary
     *
     * @return the value of adjustsalary.beforeSalary
     *
     * @mbg.generated
     */
    public Integer getBeforesalary() {
        return beforesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.beforeSalary
     *
     * @param beforesalary the value for adjustsalary.beforeSalary
     *
     * @mbg.generated
     */
    public void setBeforesalary(Integer beforesalary) {
        this.beforesalary = beforesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.afterSalary
     *
     * @return the value of adjustsalary.afterSalary
     *
     * @mbg.generated
     */
    public Integer getAftersalary() {
        return aftersalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.afterSalary
     *
     * @param aftersalary the value for adjustsalary.afterSalary
     *
     * @mbg.generated
     */
    public void setAftersalary(Integer aftersalary) {
        this.aftersalary = aftersalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.reason
     *
     * @return the value of adjustsalary.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.reason
     *
     * @param reason the value for adjustsalary.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adjustsalary.remark
     *
     * @return the value of adjustsalary.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adjustsalary.remark
     *
     * @param remark the value for adjustsalary.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adjustsalary
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", asdate=").append(asdate);
        sb.append(", beforesalary=").append(beforesalary);
        sb.append(", aftersalary=").append(aftersalary);
        sb.append(", reason=").append(reason);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}