package com.example.entity;

import java.io.Serializable;
import java.util.Date;

public class Appraise implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.eid
     *
     * @mbg.generated
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.appDate
     *
     * @mbg.generated
     */
    private Date appdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.appResult
     *
     * @mbg.generated
     */
    private String appresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.appContent
     *
     * @mbg.generated
     */
    private String appcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraise.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appraise
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.id
     *
     * @return the value of appraise.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.id
     *
     * @param id the value for appraise.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.eid
     *
     * @return the value of appraise.eid
     *
     * @mbg.generated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.eid
     *
     * @param eid the value for appraise.eid
     *
     * @mbg.generated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.appDate
     *
     * @return the value of appraise.appDate
     *
     * @mbg.generated
     */
    public Date getAppdate() {
        return appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.appDate
     *
     * @param appdate the value for appraise.appDate
     *
     * @mbg.generated
     */
    public void setAppdate(Date appdate) {
        this.appdate = appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.appResult
     *
     * @return the value of appraise.appResult
     *
     * @mbg.generated
     */
    public String getAppresult() {
        return appresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.appResult
     *
     * @param appresult the value for appraise.appResult
     *
     * @mbg.generated
     */
    public void setAppresult(String appresult) {
        this.appresult = appresult == null ? null : appresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.appContent
     *
     * @return the value of appraise.appContent
     *
     * @mbg.generated
     */
    public String getAppcontent() {
        return appcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.appContent
     *
     * @param appcontent the value for appraise.appContent
     *
     * @mbg.generated
     */
    public void setAppcontent(String appcontent) {
        this.appcontent = appcontent == null ? null : appcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraise.remark
     *
     * @return the value of appraise.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraise.remark
     *
     * @param remark the value for appraise.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraise
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", appdate=").append(appdate);
        sb.append(", appresult=").append(appresult);
        sb.append(", appcontent=").append(appcontent);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}